### PR TITLE
add a landing page to sandmark nightly

### PR DESCRIPTION
**Pull request by shubhamkumar13**
This PR adds a landing page to sandmark nightly which touches upon 3 things
- an intro to how sandmark nightly works and what it is, what kind of variants and metrics are used in each of the type of benchmark
- Machine details and description of NUMA cores
- Also stating the slow rendering speed as a disclaimer this is an unoptimized python webapp and mentioning that it might take mote time than needed to render graphs

All of the above high level details are mentioned in #29

### CODE REVIEW

**Comment by kayceesrk** [comment]
Thanks. We should also include hyperthreading in the machine stats. It is enabled on navajo and disabled on turing.

**Comment by kayceesrk** [comment]
I can't see how the page is actually rendered. Is there a way to run a local instance of sandmark nightly?

**Comment by shubhamkumar13** [comment]
> I can't see how the page is actually rendered. Is there a way to run a local instance of sandmark nightly?

Yes it's in the [README](https://github.com/ocaml-bench/sandmark-nightly)

**Comment by kayceesrk** [comment]
LGTM. I'll make some edits to the notes directly.

**Comment by kayceesrk** [comment]
Please update the hyperthreading information.

**Pull request merged**
