### PR TITLE
Add webpage with perfstat output from Sandmark

### LINKED ISSUE #66: Add webpage with perfstat output from Sandmark
The [perfstat notebook](https://github.com/ocaml-bench/sandmark/pull/372) from Sandmark needs to be made as a web page in Sandmark-nightly.

### PR DESCRIPTION
**Pull request by punchagan**
Closes #66

### CODE REVIEW

**Comment by shakthimaan** [comment]
At present, we only run sequential and parallel benchmarks in sandmark-nightly. In order to view the perf stat results, the sandmark-nightly custom runs need to also run perfstat. Can you create a PR for Sandmark for the same? It should be added at https://github.com/ocaml-bench/sandmark/blob/main/run_all_custom.sh#L124.

**Comment by punchagan** [comment]
Sure, I'll work on that. Do we want to keep this PR waiting until that PR is created? I think this can be merged independently of that, right?

**Comment by shakthimaan** [comment]
>  Do we want to keep this PR waiting until that PR is created?
Yes.
>  I think this can be merged independently of that, right?
It will be an empty page? It is better to finish the backend, get data, and then display the same in the frontend.

**Comment by punchagan** [comment]
> It will be an empty page? It is better to finish the backend, get data, and then display the same in the frontend.

I've added data from the initial run by @kayceesrk. But, sure we can wait until we configure sandmark to run the builds.

**Comment by kayceesrk** [comment]
I would classify this feature as high-priority. 

For example, as you can see there are swings in the runtime results in https://github.com/ocaml/ocaml/pull/11506. I suspect that if you had instructions retired, the swings will be gone.

**Comment by punchagan** [comment]
I've updated this PR on top of the latest `main` branch which includes the `perfstat` data from this [PR](https://github.com/ocaml-bench/sandmark/pull/394)

**Comment by shakthimaan** [comment]
LGTM!

**Comment by kayceesrk** [comment]
Great. Thanks 🙏 You should make an announcement on discuss about the perf stat data. In particular, for users, now they are able to see instructions retired in addition to running times.

**Pull request merged**
